FROM quay.io/wildfly/wildfly:28.0.0.Final-jdk17

# Copy WAR file
COPY target/test-app*.war /opt/jboss/wildfly/standalone/deployments/ROOT.war

# Create traces directory
RUN mkdir /tmp/traces

EXPOSE 8080

CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0"]
