FROM tomcat:10.0-jdk17-temurin

# Remove default webapps
RUN rm -rf /usr/local/tomcat/webapps/*

# Copy WAR file
COPY target/test-app*.war /usr/local/tomcat/webapps/ROOT.war
RUN mkdir /tmp/traces
EXPOSE 8080
CMD ["catalina.sh", "run"]
